-- V10: Walk-in session schema + seed essential reference data
--
-- 1. walk_in_sessions table (per-customer session scoping)
-- 2. walk_in_session_id column on orders
-- 3. Seed restaurant tables T1-T4 with explicit IDs 1-4
--    The frontend extracts the number from "T1" and sends tableId=1,
--    so table_id MUST match the numeric suffix.

-- ── walk_in_sessions ───────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS walk_in_sessions (
    session_id  BIGSERIAL PRIMARY KEY,
    table_id    INTEGER NOT NULL,
    created_at  TIMESTAMP DEFAULT NOW()
);

-- ── walk_in_session_id column on orders ────────────────────────────────────────
ALTER TABLE orders
    ADD COLUMN IF NOT EXISTS walk_in_session_id BIGINT;

-- ── Restaurant tables T1-T4 with explicit IDs 1-4 ─────────────────────────────
-- ON CONFLICT makes re-runs safe.
INSERT INTO restaurant_table (table_id, table_number, capacity, status)
VALUES
    (1, 'T1', 4, 'AVAILABLE'),
    (2, 'T2', 4, 'AVAILABLE'),
    (3, 'T3', 4, 'AVAILABLE'),
    (4, 'T4', 4, 'AVAILABLE')
ON CONFLICT (table_id) DO NOTHING;

-- ── Reset the ID generator so auto-inserts start after our seeded IDs ──────────
-- Hibernate 6+ (Spring Boot 3/4) uses GENERATED BY DEFAULT AS IDENTITY.
-- Hibernate 5 (Spring Boot 2) uses SERIAL sequences.
-- We try both; one will succeed silently, the other will be caught and ignored.
DO $$
DECLARE
    seq_name TEXT;
    max_id   INTEGER;
BEGIN
    SELECT GREATEST(COALESCE(MAX(table_id), 0), 4) INTO max_id FROM restaurant_table;

    -- Approach 1: GENERATED AS IDENTITY (Hibernate 6+)
    BEGIN
        EXECUTE format(
            'ALTER TABLE restaurant_table ALTER COLUMN table_id RESTART WITH %s',
            max_id + 1
        );
    EXCEPTION WHEN OTHERS THEN
        NULL; -- Not an identity column; try the sequence approach below
    END;

    -- Approach 2: SERIAL sequence (Hibernate 5)
    SELECT pg_get_serial_sequence('restaurant_table', 'table_id') INTO seq_name;
    IF seq_name IS NOT NULL THEN
        PERFORM setval(seq_name, max_id, true);
    END IF;
END $$;
